parameters:
    jquery_path: src/WeavingTheWeb/Bundle/DashboardBundle/Resources/public/components/jquery/dist/jquery.min.js

assetic:
    debug:          %kernel.debug%
    use_controller: true
    node:           %assetic_node%
    node_paths:     [ %assetic_node_module% ]
    filters:
        cssrewrite:
            apply_to:   "\.css"
        less:
            apply_to:   "\.less$"

sp_bower:
    install_on_warmup:  false
    keep_bowerrc:       false
    bin:                %bower_binary%
    assetic:
        enabled:        false
    bundles:
        WeavingTheWebDashboardBundle:
            config_dir: Resources/config/bower
            asset_dir:  ../../public/components
            json_file:  bower.json
            endpoint:   %bower_endpoint%

braincrafted_bootstrap:
    assets_dir:     %kernel.root_dir%/../node_modules/bootstrap
    jquery_path:    %kernel.root_dir%/../%jquery_path%
    less_filter:    less # "less", "lessphp", "sass" or "none"
    auto_configure:
        assetic:    true
        twig:       true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
