fos_rest:
    allowed_methods_listener: true

    param_fetcher_listener:   true

    routing_loader:
        default_format:       json

    service:
        view_handler: weaving_the_web.api.view_handler

    view:
        formats:
            json: true
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.weaving-the-web.org+json']
        force_redirects:
            html: true
        view_response_listener: force

    format_listener:
        default_priorities:
            - json
            - html
            - '*/*'
        fallback_format:      json
        prefer_extension:     true

fos_twitter:
    file:                 %kernel.root_dir%/../vendor/kertz/twitteroauth/twitteroauth/twitteroauth.php
    consumer_key:         %api_twitter_consumer_key%
    consumer_secret:      %api_twitter_consumer_secret%
    callback_url:         %api_twitter_callback_url%
