jms_security_extra:
    secure_all_services: false
    expressions: true

jms_di_extra:
    locations:
        bundles: [WeavingTheWebApiBundle]
        directories: ["%kernel.root_dir%/../src"]

security:
    encoders: %encoders%

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_user, fos_twitter]

        in_memory:
            memory:
                users:
                    %api_wtw_repositories_user_name%:
                        password: %api_wtw_repositories_password%
                        roles: [ROLE_ADMIN]
                    %api_wtw_repositories_user_name_super%:
                        password: %api_wtw_repositories_password%
                        roles: [ROLE_SUPER_ADMIN]

        fos_twitter:
            id: weaving_the_web_user.twitter_user_provider

        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        twitter_connect:
            context:                weaving_the_web
            pattern:                ^/twitter
            fos_twitter:
                login_path:         /twitter/connect
                check_path:         /twitter/login_check
                provider:           chain_provider
            logout:                 true
            anonymous:              true

        basic_connect:
            context:                weaving_the_web
            pattern:                %basic_auth_pattern%
            http_basic:
                realm:              "Please enter your login information for Weaving the Web"
                provider:           chain_provider
            anonymous:              false
            logout:
                path:               /basic/logout
                target:             /
                handlers:           [ wtw.user.security_controller ]

        api:
            pattern:                ^/api/(twitter|perspective|job)
            fos_oauth:              true
            stateless:              true
            anonymous:              false

        wtw_connect:
            context:                weaving_the_web
            pattern:                ^/(perspective/.*/export)?
            form_login:
                check_path:         fos_user_security_check
                csrf_provider:      form.csrf_provider
                login_path:         /
                provider:           fos_user
            logout:                 true
            anonymous:              ~

        # This firewall should remain beneath "wtw_connect" and "basic_connect" firewalls
        # to prevent raising an instance of "InsufficentAuthenticationException" exception
        perspective:
            pattern:                ^/perspective
            anonymous:              true
            stateless:              true

        login_failure:
            pattern:                ^/twitter/could-not-login
            anonymous:              true

        oauth_token:
            pattern:                ^/oauth/v2/token
            security:               false

        oauth_authorize:
            pattern:                ^/oauth/v2/auth
            form_login:
                check_path:         fos_user_security_check
                csrf_provider:      form.csrf_provider
                login_path:         /
                provider:           fos_user
            anonymous:              true

        dev:
            pattern:                ^/(_(profiler|wdt)|css|images|js)/
            security:               false

    access_control:
        - { path: ^/api/job,                      role: ROLE_SUPER_ADMIN }
        - { path: ^/api/perspective,              role: ROLE_SUPER_ADMIN }
        - { path: ^/api/twitter,                  role: IS_AUTHENTICATED_FULLY }
        - { path: ^/api,                          role: ROLE_USER}
        - { path: ^/_uploader,                    role: ROLE_SUPER_ADMIN }
        - { path: ^/content,                      role: ROLE_SUPER_ADMIN }
        - { path: ^/debug,                        role: ROLE_SUPER_ADMIN }
        - { path: ^/doc/,                         role: ROLE_SUPER_ADMIN }
        - { path: ^/documents,                    role: ROLE_SUPER_ADMIN }
        - { path: ^/mail,                         role: ROLE_SUPER_ADMIN }
        - { path: ^/perspective/.*/export,        role: ROLE_SUPER_ADMIN }
        - { path: ^/query,                        role: ROLE_SUPER_ADMIN }
        - { path: ^/tweet,                        role: ROLE_SUPER_ADMIN }
        - { path: ^/settings/oauth,               role: ROLE_ADMIN }
        - { path: ^/settings/remote,              role: ROLE_ADMIN }
        - { path: ^/search,                       role: ROLE_USER }
        - { path: ^/user,                         role: ROLE_USER }
        - { path: ^/,                             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basic/logout,                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,                       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/perspective,                  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                    role: IS_AUTHENTICATED_ANONYMOUSLY }
