jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WTW\UserBundle\Tests\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory]
        in_memory:
            memory:
                users:
                    %api_wtw_repositories_user_name%:
                        password: '%api_wtw_repositories_password%'
                        roles: [ROLE_ADMIN]
                    %api_wtw_repositories_user_name_super%:
                        password: '%api_wtw_repositories_password%'
                        roles: [ROLE_SUPER_ADMIN]

    firewalls:
        basic_connect:
            context:              weaving_the_web
            pattern:              '%basic_auth_pattern%'
            http_basic:
                realm:            "Please enter your login information for Weaving the Web"
                provider:         chain_provider
            anonymous:            false
            logout:
                path:             /basic/logout
                target:           /
        dev:
            pattern:              ^/(_(profiler|wdt)|css|images|js)/
            security:             false

    access_control:
        - { path: ^/api,          role: ROLE_USER }
        - { path: ^/tweet,        role: ROLE_SUPER_ADMIN }
        - { path: ^/,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basic/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
