imports:
    - { resource: ../extensions/assets.yml }
    - { resource: ../extensions/friendofsymfony.yml }
    - { resource: ../extensions/dbal.yml }
    - { resource: ../parameters.php }
    - { resource: ../parameters.yml }
    - { resource: ../extensions/security.yml }

snc_redis:
    clients:
        default:
            alias:        default
            dsn:          redis://localhost
            logging:      %kernel.debug%
            type:         predis
        session:
            type:         predis
            alias:        session
            dsn:          redis://localhost
    session:
        client:           session
        ttl:              1200
framework:


framework:
    csrf_protection:      true
    default_locale:       %locale%
    esi:                  { enabled: true }
    form:                 true
    fragments:            { path: /_fragment }
    secret:               %secret%
    router:
        resource: "%kernel.root_dir%/config/routing/routing.yml"
        strict_requirements: %kernel.debug%
    session:              ~
    templating:           { engines: ['twig'] }
    trusted_proxies:      [127.0.0.1]
    translator:           { fallback: en }
    validation:           { enable_annotations: true }

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:submit_widget.html.twig'
            - ':Form:form_errors.html.twig'
            - ':Form:form_label.html.twig'

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# Swiftmailer Configuration
swiftmailer:
    spool:     { type: memory }
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

ornicar_apc:
    host: %apc_host%
    mode: curl
    web_dir: %kernel.root_dir%/../web

parameters:
    basic_auth_pattern: /this-route-is-undefined-in-production
