imports:
    - { resource: config_dev.yml }
    - { resource: ../parameters/parameters_test.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing/routing_test.yml" }
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false
