imports:
    - { resource: ../parameters.yml }
    - { resource: ../extensions/assets.yml }
    - { resource: ../extensions/dbal.yml }
    - { resource: ../extensions/friendsofsymfony.yml }
    - { resource: ../extensions/messaging.yml }
    - { resource: ../extensions/security.yml }

framework:
    csrf_protection:          true
    default_locale:           %locale%
    esi:                      { enabled:     true }
    form:                     true
    fragments:                { path:     /_fragment }
    secret:                   %framework_secret%
    router:
        resource:             "%kernel.root_dir%/config/routing/routing.yml"
        strict_requirements:  %kernel.debug%
    session:    
        save_path:            %kernel.root_dir%/var/sessions
    templating:               { engines:     ['twig'] }
    trusted_proxies:          [127.0.0.1]
    translator:               { fallback:     en }
    validation:               { enable_annotations:     true }

ornicar_apc:
    host: %apc_host%
    mode: curl
    web_dir: %kernel.root_dir%/../web

snc_redis:
    clients:
        default:
            alias:        default
            dsn:          redis://localhost
            logging:      %kernel.debug%
            type:         predis
        session:
            type:         predis
            alias:        session
            dsn:          redis://localhost
    session:
        client:           session
        ttl:              1200

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:submit_widget.html.twig'
            - ':Form:form_errors.html.twig'
            - ':Form:form_label.html.twig'
    globals:
        feature_toggling:
            search: %feature_toggling_search%

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

parameters:
    basic_auth_pattern: /this-route-is-undefined-in-production

services:
    fos_user.mailer.default:
        class: FOS\UserBundle\Mailer\NoopMailer
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }