imports:
    - { resource: config_prod.yml }
    - { resource: ../parameters/parameters_test.yml }

doctrine:
    dbal:
        driver:           pdo_sqlite
        charset:          UTF8
        memory:           %test_database_memory%
        path:             %test_database_path%
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    WTWUserBundleTest:
                        dir: %kernel.root_dir%/../src/WTW/UserBundle/Tests/Security/Core/User
                        prefix: WTW\UserBundle\Tests\Security\Core\User
                        type: annotation
                        is_bundle: false

framework:
    profiler:
        collect: false
    test: ~