general:
  branches:
    only:
      - deploy

machine:
  timezone:
    Europe/Paris
  node:
    version: 4.2.2
  php:
    version: 5.5.11

dependencies:
  override:
    - npm install --dev

test:
  override:
    - npm test
