disclaimers:
  -
    any_suggestion
fields:
  -
    name: hash
    type: hidden
    save.to: db.feedback.hash
    value: 'md5(type,title,body)'  
  -
    name: title
    accesskey: t
    id: title
    save.to: db.feedback.title
    tabindex: 1    
    type: text*
  -
    name: type
    accesskey: y
    id: type
    provide.with.options: type    
    save.to: db.feedback.type
    tabindex: 0
    type: select*
  -
    name: body 
    accesskey: b
    cols: 70
    id: message
    rows: 5
    save.to: db.feedback.body
    tabindex: 2
    type: textarea*
  -
    accesskey: sf
    id: submit_feedback
    name: submit_feedback
    tabindex: 3
    type: submit
    value: send_feedback
options:
  type:
    1: i18n.malfunction*
    2: i18n.performance_issues
    3: i18n.epic_fail
    4: i18n.improvement
    5: i18n.feature_request
    6: i18n.other
feedback:
  success:
    message: success
  failure:
    message: failure
