tabs:
  - 
    affordance: edit.basic.information
    menu: contact_information
    type: form
  - 
    affordance: change.password
    menu: alter_password
    type: form
  - 
    affordance: send.document
    menu: upload_photograph
    type: form