parameters:
    database_charset_admin:   %database_charset%
    database_driver_admin:    pdo_mysql
    database_host_admin:      %mysql.host%
    database_port_admin:      %mysql.port%
    database_name_admin:      %mysql.database%
    database_user_admin:      %mysql.admin_user%
    database_password_admin:  %mysql.admin_password%

    database_charset:         %database_charset%
    database_driver:          pdo_mysql
    database_host:            %mysql.host%
    database_port:            %mysql.port%
    database_name:            %mysql.database%
    database_user:            %mysql.user%
    database_password:        %mysql.password%

    database_charset_read:    %database_charset%
    database_driver_read:     pdo_mysql
    database_host_read:       %mysql.host_read%
    database_port_read:       %mysql.port_read%
    database_name_read:       %mysql.database_read%
    database_user_read:       %mysql.user_read%
    database_password_read:   %mysql.password_read%
    
    database_charset_write:   %database_charset%
    database_driver_write:    pdo_mysql
    database_host_write:      %mysql.host_write%
    database_port_write:      %mysql.port_write%
    database_name_write:      %mysql.database_write%
    database_user_write:      %mysql.user_write%
    database_password_write:  %mysql.password_write%

    database_charset_test:    %database_charset%
    database_driver_test:     pdo_mysql
    database_host_test:       %mysql.host%
    database_port_test:       %mysql.port%
    database_name_test:       %mysql.test_database%
    database_user_test:       %mysql.test_user%
    database_password_test:   %mysql.test_password%
