parameters:
    api_twitter_host_port:         %api.twitter.protocol%%api.twitter.host_port%

    api_twitter_callback_url:      %api.twitter.callback_url%/twitter/login_check
    api_twitter_consumer_key:      %api.twitter.consumer_key%
    api_twitter_consumer_secret:   %api.twitter.consumer_secret%
    api_twitter_user_secret:       %api.twitter.user_secret%
    api_twitter_user_token:        %api.twitter.user_token%
    api_twitter_version:           1.1

    endpoint_twitter_feed:      %api_twitter_host_port%/api/api.twitter.display.wall.php?twr=1&res=timeline
    endpoint_twitter_user:      https://userstream.twitter.com/%s/user.json