parameters:
    rabbitmq_user:              %rabbitmq.user%
    rabbitmq_password:          %rabbitmq.password%
    rabbitmq_port:              5672
    rabbitmq_host:              %rabbitmq.host%
    rabbitmq_vhost:             %rabbitmq.vhost%
