parameters:
    facebook_redirect_url:          ~
    facebook_app_id:                ~
    facebook_app_secret:            ~
    facebook_oauth_token:           ~

    php_binary:                     /usr/bin/php
