parameters:
    api_wtw_repositories_items_per_page:    30
    api_wtw_repositories_user_name:         adama
    api_wtw_repositories_user_name_super:   super_adama
    api_wtw_repositories_password:          %quality_assurance.password%
