parameters:
    rabbitmq_user:              %rabbitmq.user%
    rabbitmq_password:          %rabbitmq.password%
    rabbitmq_port:              5672
    rabbitmq_host:              localhost
    rabbitmq_vhost:             'weaving_the_web'
