parameters:
    api_facebook_host_port:     %api.facebook.protocol%%api.facebook.host_port%
    endpoint_facebook_feed:     %api_facebook_host_port%/api/facebook/api.facebook.get.feed.php

    api_facebook_app_id:        ~
    api_facebook_app_secret:    ~
