parameters:
    assetic_node:               %assetic.node%
    assetic_node_module:        %assetic.modules%
    bower_binary:               %assetic_node_module%/bower/bin/bower
    bower_endpoint:             https://bower.herokuapp.com