imports:
    - { resource: config.yml }

framework:
    router:
        strict_requirements: null
    framework:
        esi:  true

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:         group
            members:      [streamed, buffered]
        streamed:
            type:         stream
            path:         "%kernel.logs_dir%/%kernel.environment%.log"
            level:        debug
        buffered:
            type:         buffer
            handler:      swift
        swift:
            type:         swift_mailer
            from_email:   exceptions@weaving-the-web.org
            to_email:     thierry.marianne@weaving-the-web.org
            subject:      "[Weaving the Web] Snaps, something went wrong :/"
            level:        debug
