doctrine:
    dbal:
        driver:           pdo_sqlite
        charset:          UTF8
        memory:           %test_database_memory%
        path:             %test_database_path%

imports:
    - { resource: config_dev.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_test.yml" }
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

parameters:
    basic_auth_pattern: ^/(documents|github|settings)
    database_charset:   UTF8
    database_driver:    pdo_mysql
    database_host:      %database_host_test%
    database_port:      %database_port_test%
    database_name:      %database_name_test%
    database_user:      %database_user_test%
    database_password:  %database_password_test%
    security.user.provider.in_memory.class:       WTW\UserBundle\Tests\Security\Core\User\InMemoryUserProvider
    security.user.provider.in_memory.user.class:  WTW\UserBundle\Tests\Security\Core\User\User
    wtw.data_mining.command_provider.class:       WTW\API\DataMiningBundle\Command\Tester\TransformationCommandProvider

services:
    fos_user.mailer.default:
        class: FOS\UserBundle\Mailer\NoopMailer
