imports:
    - { resource: assets.yml }
    - { resource: friendofsymfony.yml }
    - { resource: dbal.yml }
    - { resource: parameters.php }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    default_locale:       %locale%
    translator:           { fallback: en }
    secret:               %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:                 true
    csrf_protection:      true
    validation:           { enable_annotations: true }
    templating:           { engines: ['twig'] }
    session:              ~

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - ':Form:submit_widget.html.twig'
            - ':Form:form_errors.html.twig'
            - ':Form:form_label.html.twig'

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# Swiftmailer Configuration
swiftmailer:
    spool:     { type: memory }
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

ornicar_apc:
    host: %apc_host%
    mode: curl
    web_dir: %kernel.root_dir%/../web

parameters:
    basic_auth_pattern: /this-route-is-undefined-in-production
