
# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                charset:  %database_charset%
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
            admin:
                charset:  %database_charset_admin%
                driver:   %database_driver_admin%
                host:     %database_host_admin%
                dbname:   %database_name_admin%
                user:     %database_user_admin%
                password: %database_password_admin%
            test_mysql:
                charset:  %database_charset_test%
                driver:   %database_driver_test%
                host:     %database_host_test%
                dbname:   %database_name_test%
                user:     %database_user_test%
                password: %database_password_test%
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    WTWCodeGenerationAnalysisBundle: ~
                    WTWDashboardBundle: ~
                    WTWLegacyProviderBundle: ~
                    WTWUserBundle: ~
                    WeavingTheWebApiBundle: ~
                    WeavingTheWebUserBundle: ~
            admin:
                connection: admin
                mappings:
                    WTWCodeGenerationAnalysisBundle: ~
                    WTWDashboardBundle: ~
                    WTWUserBundle: ~
                    WTWLegacyProviderBundle: ~
                    WeavingTheWebApiBundle: ~
                    WeavingTheWebUserBundle: ~
            test_mysql:
                connection: test_mysql
                mappings:
                    WTWCodeGenerationAnalysisBundle: ~
                    WTWDashboardBundle: ~
                    WTWLegacyProviderBundle: ~
                    WTWUserBundle: ~
                    WeavingTheWebApiBundle: ~
                    WeavingTheWebUserBundle: ~
        auto_generate_proxy_classes: %kernel.debug%
