wtw_user:
    resource: "@WTWUserBundle/Controller/"
    type:     annotation

wtw_registration_land:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Registration:land }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@WTWUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:   /profile

fos_user_register:
    resource: "@WTWUserBundle/Resources/config/routing/registration.xml"
    prefix:   /register

fos_user_registration_register:
    pattern:  /
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:   /profile

weaving_the_web_api:
    resource:     "@WeavingTheWebApiBundle/Resources/config/routing.yml"

weaving_the_web_dashboard:
    resource: "@WeavingTheWebDashboardBundle/Controller/"
    type:     annotation

weaving_the_web_user:
    resource: "@WeavingTheWebUserBundle/Resources/config/routing.xml"
    prefix:   /user
