jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WTW\UserBundle\Tests\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_user]
        fos_twitter:
            id: wtw.dashboard.twitter_user
        in_memory:
            memory:
                users:
                    %api_wtw_repositories_user_name%:
                        password: %api_wtw_repositories_password%
                        roles: [ROLE_ADMIN]
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        twitter_connect:
            context:              weaving_the_web
            pattern:              ^/twitter
            fos_twitter:
                login_path:       /twitter/connect
                check_path:       /twitter/login_check
                provider:         fos_twitter
            logout:               true
            anonymous:            true
        basic_connect:
            context:              weaving_the_web
            pattern:              %basic_auth_pattern%
            http_basic:
                realm:            "Please enter your login information for Weaving the Web"
                provider:         chain_provider
            anonymous:            false
            logout:
                path:             /basic/logout
                target:           /
                handlers:         [ wtw.user.security_controller ]

        wtw_connect:
            context:              weaving_the_web
            pattern:              ^/
            form_login:
                provider:         fos_user
                csrf_provider:    form.csrf_provider
            logout:               true
            anonymous:            true

        login_failure:
            pattern:              ^/could-not-login
            anonymous:            true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(documents|user), role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/basic/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
