jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    %api_wtw_repositories_user_name%:
                        password: %api_wtw_repositories_password%
                        roles: [ROLE_USER]

    firewalls:
        basic_connect:
            context:              weaving_the_web
            pattern:              %basic_auth_pattern%
            http_basic:
                realm:            "Please enter your login information for Weaving the Web"
                provider:         in_memory
            anonymous:            true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
