parameters:
    weaving_the_web_twitter.api_accessor.class:                   WeavingTheWeb\Bundle\TwitterBundle\Api\Accessor
    weaving_the_web_twitter.moderator.api_limit.class:            WeavingTheWeb\Bundle\ApiBundle\Moderator\ApiLimitModerator
    weaving_the_web_twitter.api_host:                             api.twitter.com
    weaving_the_web_twitter.application_authenticator.class:      WeavingTheWeb\Bundle\TwitterBundle\Security\ApplicationAuthenticator
    weaving_the_web_twitter.authenticate_application.class:       WeavingTheWeb\Bundle\TwitterBundle\Command\AuthenticateApplicationCommand
    weaving_the_web_twitter.authentication_uri:                   /oauth2/token
    weaving_the_web_twitter.client.class:                         \Goutte\Client
    weaving_the_web_twitter.consumer_key:                         %api_twitter_consumer_key%
    weaving_the_web_twitter.consumer_secret:                      %api_twitter_consumer_secret%
    weaving_the_web_twitter.endpoint.feed:                        %endpoint_twitter_feed%
    weaving_the_web_twitter.http_client.class:                    \GuzzleHttp\Client
    weaving_the_web_twitter.oauth_client.class:                   TwitterOAuth
    weaving_the_web_twitter.oauth_token.default:                  %api_twitter_user_token%
    weaving_the_web_twitter.oauth_secret.default:                 %api_twitter_user_secret%
    weaving_the_web_twitter.repository.user_stream.class:         %weaving_the_web_api.entity.user_stream.class%
    weaving_the_web_twitter.repository.token.class:               %weaving_the_web_api.entity.token.class%
    weaving_the_web_twitter.serializer.user_status.class:         WeavingTheWeb\Bundle\TwitterBundle\Serializer\UserStatus
    weaving_the_web_twitter.serialize_statuses.class:             WeavingTheWeb\Bundle\TwitterBundle\Command\SerializeStatusesCommand
    weaving_the_web_twitter.version:                              %api_twitter_version%

services:
    weaving_the_web_twitter.application_authenticator:
        class: %weaving_the_web_twitter.application_authenticator.class%
        calls:
            - [ setupClient, [ %weaving_the_web_twitter.client.class%, %weaving_the_web_twitter.http_client.class% ] ]
        properties:
            apiHost:            %weaving_the_web_twitter.api_host%
            authenticationUri:  %weaving_the_web_twitter.authentication_uri%
            key:                %weaving_the_web_twitter.consumer_key%
            secret:             %weaving_the_web_twitter.consumer_secret%
            tokenRepository:    @weaving_the_web_twitter.repository.token
    weaving_the_web_twitter.repository.user_stream:
        class: %weaving_the_web_api.repository.user_stream.class%
        factory:    [@doctrine.orm.entity_manager, getRepository]
        arguments:  [%weaving_the_web_twitter.repository.user_stream.class%]
    weaving_the_web_twitter.repository.read.user_stream:
        class: %weaving_the_web_api.repository.user_stream.class%
        factory:    [@doctrine.orm.read_entity_manager, getRepository]
        arguments:  [%weaving_the_web_twitter.repository.user_stream.class%]
        calls:
            - [ setOauthTokens, [ [%weaving_the_web_twitter.oauth_token.default%] ] ]
    weaving_the_web_twitter.repository.token:
        class: %weaving_the_web_api.repository.token.class%
        factory:    [@doctrine.orm.entity_manager, getRepository]
        arguments:  [%weaving_the_web_twitter.repository.token.class%]
    weaving_the_web_twitter.repository.read.token:
        class: %weaving_the_web_api.repository.token.class%
        factory:    [@doctrine.orm.read_entity_manager, getRepository]
        arguments:  [%weaving_the_web_twitter.repository.token.class%]
    weaving_the_web_twitter.api_accessor:
        class: %weaving_the_web_twitter.api_accessor.class%
        arguments:
            - @logger
        calls:
            - [ setClientClass, [ '\Goutte\Client' ] ]
            - [ setConsumerKey, [ %weaving_the_web_twitter.consumer_key% ] ]
            - [ setConsumerSecret, [ %weaving_the_web_twitter.consumer_secret% ] ]
            - [ setHttpClientClass, [ %weaving_the_web_twitter.http_client.class% ] ]
            - [ setModerator, [ @weaving_the_web_twitter.moderator.api_limit ] ]
            - [ setTokenRepository, [ @weaving_the_web_twitter.repository.token ] ]
            - [ setUserSecret, [ %weaving_the_web_twitter.oauth_secret.default% ] ]
            - [ setUserToken, [ %weaving_the_web_twitter.oauth_token.default% ] ]
            - [ setTranslator, [ @translator ] ]
        properties:
            environment: %kernel.environment%
            httpClient: %weaving_the_web_twitter.oauth_client.class%
    weaving_the_web_twitter.moderator.api_limit:
        class:  %weaving_the_web_twitter.moderator.api_limit.class%
        arguments:
            - @?logger
    weaving_the_web_twitter.serializer.user_status:
        class:  %weaving_the_web_twitter.serializer.user_status.class%
        calls:
            - [ setAccessor, [ @weaving_the_web_twitter.api_accessor ] ]
            - [ setLogger, [ @logger ] ]
            - [ setModerator, [ @weaving_the_web_twitter.moderator.api_limit ] ]
            - [ setUserStreamRepository, [ @weaving_the_web_twitter.repository.user_stream ] ]
            - [ setTokenRepository, [ @weaving_the_web_twitter.repository.token ] ]
            - [ setTranslator, [ @translator ] ]
