disclaimers:
  -
    enter_email
fields:
  -
    accesskey: e
    before.update:
      send: email.retrieve_password
      display: disclaimer.safe_changes
    class: email
    display.default.value: Email
    id: login
    name: email
    tabindex: 1
    type: email*
    update:
      name: db.user.password
      value: call.user_handler.random_password
  -
    accesskey: s
    id: submit
    name: submit
    tabindex: 3
    type: submit
    value: submit
links:
  -
    name: sign_in
    position: after
    target: form.sign_in