fields:
  -
    name: action
    type: hidden
    value: '{$affordance}'
  -
    name: target_type
    type: hidden
    value: '{$target_type}'
  -
    name: target
    type: hidden
    value: '{$target}'
  -
    name: parent
    type: hidden
    value: '{$parent}'
  -
    name: body
    cols: 120
    type: textarea*
    rows: 4
    text: '{$text}'
  -
    class: button_post_insight
    name: post
    type: submit
    value: Post