disclaimers:
  -
    requirements
fields:
  -
    accesskey: p  
    check.records: db.user.password
    name: password
    type: password*
    tabindex: 7
  -
    accesskey: n  
    after.update:
      display: disclaimer.password_has_changed
    link.to: new_password_again
    name: new_password
    type: password*
    update: sha1.db.user.password
    tabindex: 8
  -
    accesskey: c
    link.to: db.user.password
    name: new_password_again
    type: password*
    tabindex: 9    
  -
    accesskey: s
    id: submit_password
    name: submit
    tabindex: 10
    type: submit
    value: update
layout:
  title_level_2: alter_password