fields:
  -
    accesskey: i
    name: identity
    tabindex: 1
    type: password*
  -
    accesskey: c
    name: offer
    tabindex: 2
    type: password*
  -  
    accesskey: s
    id: submit
    name: submit
    tabindex: 3
    type: submit
    value: submit