fields:
  - 
    name: title
    accesskey: t    
    type: text*
  -
    name: subtitle
    accesskey: b    
    type: text
  -
    name: keywords
    accesskey: k
    type: text
  -
    name: body
    class: text
    accesskey: b
    cols: 120
    id: text
    rows: 25
    type: textarea*
  -
    name: save
    class: save
    accesskey: s    
    type: button
    value: Save
  -
    name: submit
    class: valid
    accesskey: v
    type: submit
    value: Valid