parameters:
    weaving_the_web_data_mining.miner.class:          WeavingTheWeb\Bundle\DataMiningBundle\Miner

services:
    weaving_the_web_data_mining.miner:
        class: %weaving_the_web_data_mining.miner.class%
        arguments:
          - %weaving_the_web_twitter.endpoint.feed%
        calls:
          - [ setHttpClientClass, [ '\Guzzle\Http\Client' ] ]
          - [ setClientClass, [ '\Goutte\Client' ] ]
