---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - rabbitmq
    - elasticsearch
    - php
    - xdebug
    - composer
    - app
    - role: nvm
      nvm:
        user: vagrant
        version: v0.29.0
        node_version: v4.2.2
