---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - role: git
      git_install_from_source: true
      git_install_path: "/usr"
      git_version: "2.1.0"
    - role: server
      tags: server
    - role: vagrant
      tags: vagrant
    - role: apache
      tags: apache
    - role: varnish
      tags: varnish
    - role: mysql
      tags: mysql
    - role: rabbitmq
      tags: rabbitmq
    - elasticsearch
    - role: php
      tags: php
    - xdebug
    - composer
    - redis
    - role: nvm
      nvm:
        user: vagrant
        version: v0.29.0
        node_version: v4.2.2
    - role: app
      tags: app
