_main:
    resource: routing.yml

weaving_the_web_twitter:
    resource: "@WeavingTheWebUserBundle/Controller/"
    type:     annotation

weaving_the_web_user:
    prefix:   /user
    resource: "@WeavingTheWebUserBundle/Tests/Resources/config/routing_test.xml"
