_main:
    resource: routing.yml

weaving_the_web_twitter:
    resource: "@WeavingTheWebUserBundle/Controller/"
    type:     annotation

weaving_the_web_documentation_markdown:
    resource:     "@WeavingTheWebDocumentationMarkdownBundle/Controller"
    type:         annotation
