fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@WTWUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    prefix:   /profile
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"

fos_user_register:
    prefix:   /register
    resource: "@WTWUserBundle/Resources/config/routing/registration.xml"

fos_user_registration_register:
    defaults: { _controller: FOSUserBundle:Registration:register }
    pattern:  /

fos_user_resetting:
    prefix:   /resetting
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_change_password:
    prefix:   /profile
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
