---
- name: remove the verification key for the package
  apt_key:
    id: 056E8E56
    state: absent

- name: add the verification key for the package
  apt_key:
    url: http://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    state: present

- name: add rabbitmq official apt repository
  apt_repository:
    repo: deb http://www.rabbitmq.com/debian/ testing main
    state: present

- name: update repositories
  apt: update_cache=yes

- name: install rabbitmq
  apt: pkg=rabbitmq-server state=installed force=yes

- name: enable rabbitmq plugins
  rabbitmq_plugin: names={{ item }} state=enabled
  with_items: rabbitmq.plugins
  when: rabbitmq.plugins is defined

- name: add user
  rabbitmq_user:
    user: "{{ rabbitmq.user }}"
    password: "{{ rabbitmq.password }}"
    node: "rabbit@{{ vagrant_local.vm.hostname }}"
    tags: "administrator,{{ rabbitmq.user }},monitoring,management"
    vhost: "/"
    configure_priv: ".*"
    write_priv: ".*"
    read_priv: ".*"
    state: "present"

- name: restart rabbitmq
  service: name=rabbitmq-server state=reloaded
